# Generated by Django 5.2.15 on 2026-07-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('CLAIMED', 'CLAIMED'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='QUEUED', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('is_dead_letter', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='queues.queue')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'), models.Index(fields=['scheduled_at'], name='jobs_job_schedul_e24bae_idx')],
            },
        ),
    ]
