# Generated by Django 5.2.15 on 2026-07-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_job_jobexecution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobexecution',
            name='job',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobExecution',
        ),
    ]
