# Generated by Django 5.2.15 on 2026-07-02 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='worker',
            name='heartbeat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(default='IDLE', max_length=20),
        ),
    ]
